In [3]:
import numpy as np

In [4]:
mylist = [1,2,3,4]

In [5]:
myarray = np.array(mylist)

In [6]:
myarray

array([1, 2, 3, 4])

In [7]:
mylist2 = [11,22,33,44]

In [8]:
mlist = [mylist,mylist2]

In [9]:
array = np.array(mlist)

In [10]:
array

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [11]:
array.shape

(2, 4)

In [12]:
array.dtype

dtype('int32')

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
za = np.zeros(5)

In [15]:
za.dtype

dtype('float64')

In [16]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.empty(5)

array([2.12199579e-314, 2.41907520e-312, 5.19757059e-321, 3.79442416e-321,
       0.00000000e+000])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [20]:
from __future__ import division

In [21]:
5/2

2.5

In [22]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])

In [23]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
arr1*arr1

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [25]:
arr1-arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [26]:
1 / arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ]])

In [27]:
arr1**3

array([[  1,   8,  27,  64],
       [125, 216, 343, 512]], dtype=int32)

In [28]:
arr  =np.arange(0,11)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr[1:5]

array([1, 2, 3, 4])

In [31]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [32]:
arr[0:5] = 100

In [33]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [34]:
slice_arr = arr[0:6]

In [35]:
slice_arr

array([100, 100, 100, 100, 100,   5])

In [36]:
slice_arr[:] = 99

In [37]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [38]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [39]:
arr_copy = arr.copy()

In [40]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [41]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [42]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [43]:
arr_2d[0][1]

10

In [44]:
arr_2d[0][1]

10

In [45]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [46]:
def func():
    for row in arr_2d:
        for value in row:
            print(value)

In [47]:
mlist = func()

5
10
15
20
25
30
35
40
45


In [48]:
mlist

In [49]:
#fancy indexing

In [50]:
arr2d = np.zeros((10,10))

In [51]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [52]:
arr_lenght = arr2d.shape[1]

In [53]:
arr_lenght

10

In [54]:
for i in range(arr_lenght):
    arr2d[i]=i

In [55]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [56]:
#array transposition

In [57]:
arr = np.arange(50).reshape((10,5))

In [58]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [59]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [60]:
np.dot(arr.T,arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [61]:
arr3d = np.arange(50).reshape((5,5,2))

In [62]:
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [63]:
arr3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49]]])

In [64]:
arr = np.array([1,2,3])

In [65]:
arr

array([1, 2, 3])

In [66]:
arr.swapaxes(1,1)

AxisError: axis1: axis 1 is out of bounds for array of dimension 1

In [ ]:
num = int(arr[0][1])

In [ ]:
ar = np.arange(0,50)

In [ ]:
ar

In [ ]:
counter = 0

for obj in ar:
    counter += 1
    

In [ ]:
counter

In [ ]:
arr = np.arange(11)

In [ ]:
arr

In [ ]:
print(arr)

In [ ]:
arr[0]

In [ ]:
np.sqrt(arr)

In [ ]:
np.exp(arr)

In [ ]:
print("hola")

In [ ]:
def arr_len(arr):
    
    count = 0
    
    for obj in arr:
        count += 1
        
    return count

In [ ]:
arr_len(arr)

In [ ]:
A = np.random.randn(10)

In [ ]:
A

In [ ]:
B = np.random.randn(10)

In [ ]:
B

In [ ]:
np.add(A,B)

In [ ]:
np.maximum(A,B)

In [ ]:
np.array("hola")

In [ ]:
np.minimum(A,B)

In [ ]:
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"

In [ ]:
import webbrowser
webbrowser.open(website)

AttributeError: 'numpy.ndarray' object has no attribute 'append'